source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'rake','0.8.7'
gem 'compass'
gem 'haml'
gem 'sass', '3.1.3'

gem 'actionmailer', '3.0.6'
gem 'mail', '2.2.19'
gem 'activesupport', '3.0.6'
gem 'email_veracity_checker'

gem 'event-calendar', '2.3.3', :require => "event_calendar"

gem 'rack-ssl', :require => 'rack/ssl'

gem 'date_validator'
gem 'will_paginate'

gem "jquery-rails"

# Bundle edge Rails instead:
# gem 'rails', :git  => 'git://github.com/rails/rails.git'



# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
 
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
 group :development do
   gem 'sqlite3-ruby', :require => 'sqlite3'
   gem 'rspec-rails', '2.0.1'
   gem 'annotate', '2.4.0'
   gem 'ruby-debug-base19x'
   gem 'ruby-debug-ide19'
 end

 group  :test do
   #gem 'rspec', '2.0.1'
   gem 'webrat', '0.7.1'
   gem 'spork' , '0.8.4'
   #gem 'factory_girl_rails', '1.0.1'
 end
